name: Trigger auto deployment for container-app-tnwzcc3vm3woc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '.devcontainer/**'
    - '.github/workflows/container-app-tnwzcc3vm3woc-AutoDeployTrigger-c6d0c6a5-8c82-429b-97a3-ca7218df02dc.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerregistrytnwzcc3vm3woc.azurecr.io
          username: ${{ secrets.CONTAINERAPPTNWZCC3VM3WOC_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINERAPPTNWZCC3VM3WOC_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerregistrytnwzcc3vm3woc.azurecr.io/container-app-tnwzcc3vm3woc:${{ github.sha }}
          file: ./.devcontainer/Dockerfile
          context: ./.devcontainer/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPTNWZCC3VM3WOC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPTNWZCC3VM3WOC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPTNWZCC3VM3WOC_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n container-app-tnwzcc3vm3woc -g todojavamongoacawo9f3a --server containerregistrytnwzcc3vm3woc.azurecr.io --username  ${{ secrets.CONTAINERAPPTNWZCC3VM3WOC_REGISTRY_USERNAME }} --password ${{ secrets.CONTAINERAPPTNWZCC3VM3WOC_REGISTRY_PASSWORD }}
            az containerapp update -n container-app-tnwzcc3vm3woc -g todojavamongoacawo9f3a --image containerregistrytnwzcc3vm3woc.azurecr.io/container-app-tnwzcc3vm3woc:${{ github.sha }}
